version: '3'


services:
  db:
    container_name: db
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  bot:
    container_name: bot
    build: .
    env_file: .env
    volumes:
      - bot_data:/app
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data:
  bot_data:
